### ISSUE TITLE
How is this module useful?

### ISSUE THREAD

**Issue by Akuli** [wbolster/jsonlines#29]
Hi,

I don't see how this 350-line library is better than `map(json.loads, f)` and `print(json.dumps(...), file=f)`, where `f` is a file object opened with `encoding='utf-8'`. As far as I can tell, the `map` and `print` solutions are fully compatible with [the jsonlines standard](http://jsonlines.org/).

Thanks.

**Comment by Zaab1t** [comment]
I'm not the dev, but this is still a little heartbreaking.

**Comment by wbolster** [comment]
oh wow. i did not realise that my library is bullshit.

yeah, indeed, you are very smart and your one-liners are very flexible and readable and maintainable.

oh wait. it doesn't work the same on python 2.

oh wait, it doesn't flush the underlying stream.

oh wait, you have to specify `sort_keys=True` every time to write a line.

oh wait, 3 lines of code is better than 350 lines of code. (have you read those? mostly docstrings and convenience helpers, not much code at all actually.)

oh wait, you cannot verify that type of json object you get from your stream.

oh wait, the exception does not tell you which line was erroneous while parsing this 10GB input file.

____

lemme quote [the first paragraph of the docs](https://jsonlines.readthedocs.io/) since it seems you did not bother to read them.

> This data format is straight-forward: it is simply one valid JSON value per line, encoded using UTF-8. While code to consume and create such data is not that complex, it quickly becomes non-trivial enough to warrant a dedicated library when adding data validation, error handling, support for both binary and text streams, and so on. This small library implements all that (and more!) so that applications using this format do not have to reinvent the wheel.

oh wow, so it kinda makes sense after all. now read about the features (you will have to click yourself this time): https://jsonlines.readthedocs.io/en/latest/#features

____

thanks for your valuable feedback. i especially the friendly way you phrased it.

**Comment by Akuli** [comment]
Thanks for making things clear, and sorry for not reading the docs. :( I guess I expected to see something like that first paragraph in the README.

Now I see how this can be useful. I especially like the type-checking part: the json module itself doesn't do any kind of sanity checks, and [not everyone like it that way](https://jeffknupp.com/blog/2016/11/13/how-python-makes-working-with-data-more-difficult-in-the-long-run/).

At first I was surprised by the need of a website for something as simple as JSON on each line of a file, so I was even more surprised to see a library for parsing and writing that.

**Comment by wbolster** [comment]
it's ok @Akuli.  may i count you among the happy users from today on? :)

that said, since you indicated you like some more type checking, you may be interested in my latest json related project, named `sanest`, which provides sane nested dictionaries and lists. do read the docs though since they explain a lot of the 'why' questions you may have... ;) https://sanest.readthedocs.io/

**Comment by Akuli** [comment]
To be honest I don't work with JSON *that* often, and when I do my map and print things will probably be enough for me (even though obviously not for everyone else).
