### ISSUE TITLE
Support for open mode "r+"

### ISSUE THREAD

**Issue by YYLIZH** [wbolster/jsonlines#79]
Hi,
Thanks for making this useful package.

I am wondering if the "open" method can support with mode r+. Maybe by implenting an "Updater"?
I am working on a project, which needs to manage a jsonline file which act as a small database. Processes need to use the data in the jsonline file to do some calculation and update in the same line of jsonlines. Thus I need to read and write the jsonline file at the same time.

**Comment by wbolster** [comment]
near-duplicate of #72

see especially https://github.com/wbolster/jsonlines/issues/72#issuecomment-1165364945

what do you want to achieve exactly? because you can likely achieve that in your application code by opening the for yourself, and delegating reading/writing logic to a reader/writer (flush!) by passing it the open file

**Comment by YYLIZH** [comment]
Got it. This method solves my problems. Thank you very much.
